language: node_js
node_js:
- 6.2.0
script:
- npm run build
cache:
  bundler: true
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: iW+zRkwzvppzITp+mo3beC9/yYCcfk7yha03aNtvE2LFaWg/ynqZvJ6z3Z1jbTALj7/S5IwssVTJywJCqFNRH7+ks2VtbJ2Zh7N+fy9kVGKIw32GW2dF4+wq4tbpfIuBUOeb+3xpIGqvbA2vOTDtT5/IInUyXSZLUQFv/T3b5LlobGC63B4gpv2gPbEcvcHy+6HhkJFf3znarZq/xURsrnKXcjOKL4msdwOEJ1rnLITlMyvyT0NfkwNqllMaUJORwbIm3g3P/ipGZfyDZBY8AdAV2YFcjykxchVTmeDE6FYjljjkpP9gaBwjjDHcouEg1gyJ9mSUGmYDL5YWxZ2Bdcz6byorTD2msAy2GECag4Ddmqf7FiZXbwOvkOTkJRbKsna178nQD8lseqJtW6rfGvMeeqhq4tn9ABEWvl1izx6gApSjZkwwbLKDW11r5ekD2lzB7aisOfH73luWrYzkxJwCNBge8IosD3cz2aWLK68eHfCjn6fHzc7iRrQsJTBibe7Kz/pqn8BJgGrMDtP89HpJlW5EVBjmKyEeAV/ei3FFDHS0+pzgJr3guK1KTsnenacrQyvKZhIB+V3VBFD9Rd3/ysTF0lQ4p6pqzcDcvLuzsbtWzP+z9c9HPJcZYpnExrBHQ8nqBEH4Gct8w1sfYABZOkzKJnn1lYZlJoCTPrM=
