language: node_js
node_js:
- 6.2.0
script:
- npm run build
cache:
  bundler: true
  directories:
  - node_modules
addons:
  artifacts:
    paths:
    - build
deploy:
  provider: heroku
  api_key:
    secure: vz7E7x6qIYRODqysFN0f1PzqqIsJkBcpHHn3Or17RQOThBypK3zHI70GG+afkfvIml4GsWMaPhFE1iuf0AnqoN6Rid25exKimBExK72Xp73sqd++tZFhjo5ykbnxxluycAinBUuX8wrMExjeWKY7NsactE5bs/7R+rBRRqP4NiKSVa90Lh2R89Y1LN6t3yhaWTTbTTuilAixE3WgMdchYOR56KTanZkN6C3Rcfiri+k97Vz8Spyjgs3zOu3Glo12rYN/BTwSmwJjaCRzxbFimsv2R8MwJ0aGcp+2GvZM278mtP3nH7LTMjHMROVqNstXQxu4VyRVB85uFhFyVdGTnd2J3zmk5ryumKGiMvnCeaY6axI9ePrKpMSyHCtosH50UE1DvoVTiyPQkEII0BJO0vjlocEbVEHXtPWS0yrWDBgazSsglOmedL8IbhxykiASe6374BDnCv5+MRlwM4/xOU8D8Z+H/qvNrcjYIny/4FyA6tVJLAMgqgFOeYinsfe8SxXHefExsvpFQ3OXLfDnzsUSdAk7wDuk11fWeJvw9xpa5+yv6i5lKzHf1W1wCnOEExIM8nqdq0kS2PGVv2kojeju4HIpVbxlmvbaByLY07CYtd7+NUfhIxp60M5vDTQd5V87z5XqSz7PLjEo6rbjqSpGBl8tE58TpPQcyi54ubo=
  app: pickonebot
  on:
    repo: lulalachen/pickOneBot
branches:
  only:
  - master
